import * as URLS from "../urls";

export const PAGE_LEVEL = "PAGE_LEVEL";
export const CONTROL_LEVEL = "CONTROL_LEVEL";
export const USER_TYPE_ADMIN = "ADMIN";
export const USER_TYPE_SUPER_USER = "SUPER_USER";
export const USER_TYPE_WORKER = "WORKER";

export const generalAccessURLS = [];

export const pageToAccessKeyMapping = {
  [URLS.DASHBOARD_URL]: "VIEW_DASHBOARD",
  [URLS.USERS_URL]: "VIEW_USERS",
  [URLS.ORDERS_URL]: "VIEW_ORDERS",
  [URLS.PRODUCTS_URL]: "VIEW_PRODUCTS",
  [URLS.PROMOCODE_URL]: "VIEW_PROMOCODE",
  [URLS.DELIVERY_SLOT_URL]: "VIEW_DELIVERY_SLOT",
  [URLS.DELIVERY_BOY_URL]: "VIEW_DELIVERY_BOY",
  [URLS.OFFER_SETTINGS_URL]: "VIEW_OFFER_SETTINGS",
  [URLS.DELIVERY_CHARGE_URL]: "VIEW_DELIVERY_CHARGES",
  [URLS.CATEGORY_URL]: "VIEW_CATEGORY",
  [URLS.SETTINGS_URL]: "VIEW_SETTINGS",
  [URLS.TERMS_AND_CONDITIONS_URL]: "VIEW_TERMS_AND_CONDITIONS",
  [URLS.PUSH_NOTIFICATION_URL]: "VIEW_NOTIFICATIONS",
  [URLS.PRIVACY_POLICY_URL]: "VIEW_PRIVACY_SETTINGS",
  [URLS.CONTACT_US_URL]: "VIEW_CONTACT_US",
  [URLS.ADMIN_URL]: "ADMIN",
};

export const userHasAccessToKey = (userInfo, key) =>
  userInfo?.controlLevelAccess?.includes(key);

export const userHasViewAccessToRoute = (userInfo, route) =>
  userInfo?.pageLevelAccess?.includes(pageToAccessKeyMapping[route]);

export const isAdminUser = (userInfo) => {
  return [USER_TYPE_ADMIN, USER_TYPE_SUPER_USER].includes(userInfo?.userType);
};

// Control Level Access
export const CONTROL_ADD_PRODUCT = "ADD_PRODUCT";
export const CONTROL_EDIT_PRODUCT = "EDIT_PRODUCT";
export const CONTROL_DELETE_PRODUCT = "DELETE_PRODUCT";
export const CONTROL_UPDATE_DELIVERY_BOY = "UPDATE_DELIVERY_BOY";
export const CONTROL_ADD_PROMOCODE = "ADD_PROMOCODE";
export const CONTROL_EDIT_DELIVERY_SLOT = "EDIT_DELIVERY_SLOT";
export const CONTROL_ADD_DELIVERY_SLOT = "ADD_DELIVERY_SLOT";
export const CONTROL_DELETE_DELIVERY_SLOT = "DELETE_DELIVERY_SLOT";
export const CONTROL_ADD_OFFER = "ADD_OFFER";
export const CONTROL_EDIT_OFFER = "EDIT_OFFER";
export const CONTROL_DELETE_OFFER = "DELETE_OFFER";
export const CONTROL_ADD_DELIVERY_CHARGES = "ADD_DELIVERY_CHARGES";
export const CONTROL_EDIT_DELIVERY_CHARGES = "EDIT_DELIVERY_CHARGES";
export const CONTROL_DELETE_DELIVERY_CHARGES = "DELETE_DELIVERY_CHARGES";
export const CONTROL_ADD_CATEGORY = "ADD_CATEGORY";
export const CONTROL_EDIT_CATEGORY = "EDIT_CATEGORY";
export const CONTROL_DELETE_CATEGORY = "DELETE_CATEGORY";
export const CONTROL_ADD_SETTINGS = "ADD_SETTINGS";
export const CONTROL_EDIT_TERMS_AND_CONDITIONS = "EDIT_TERMS_AND_CONDITIONS";
export const CONTROL_DELETE_TERMS_AND_CONDITIONS =
  "DELETE_TERMS_AND_CONDITIONS";
export const CONTROL_ADD_FAQ = "ADD_FAQ";
export const CONTROL_EDIT_FAQ = "EDIT_FAQ";
export const CONTROL_DELETE_FAQ = "DELETE_FAQ";
export const CONTROL_ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";
export const CONTROL_ADD_PRIVACY_SETTINGS = "ADD_PRIVACY_SETTINGS";
export const CONTROL_EDIT_PRIVACY_SETTINGS = "EDIT_PRIVACY_SETTINGS";
export const CONTROL_DELETE_PRIVACY_SETTINGS = "DELETE_PRIVACY_SETTINGS";
export const CONTROL_ADD_CONTACT_DETAILS = "ADD_CONTACT_DETAILS";
export const CONTROL_ADD_VARIANT = "ADD_VARIANT";
